"""
Core Function Verification Script
Generated by Repo Genesis Auditor
"""
import json
import subprocess
import sys
from pathlib import Path
from dataclasses import dataclass
from typing import Any

@dataclass
class VerificationResult:
    function_id: str
    scenario_name: str
    passed: bool
    actual_output: Any
    expected_output: Any
    error_message: str | None = None
    interpretation: str = ""

def verify_cf005_webhook_validation() -> VerificationResult:
    """CF-005: Webhook URL validation"""
    
    # Since this is a Kotlin Android project, we can't easily import the code directly in Python.
    # We will rely on running a specific unit test that we expect to exist.
    # Ideally, this script would run './gradlew test --tests *SlackWebhookValidatorTest'
    # But for this bootstrap, we will check if the test file exists and if the tests pass via gradle.

    test_file = Path("app/src/test/java/jp/co/screentime/slackreporter/data/slack/SlackWebhookValidatorTest.kt")
    
    if not test_file.exists():
        return VerificationResult(
            function_id="CF-005",
            scenario_name="Webhook Validation Logic",
            passed=False,
            actual_output="File not found",
            expected_output="File exists",
            error_message="Unit test file SlackWebhookValidatorTest.kt does not exist",
            interpretation="Validation logic is not tested."
        )

    try:
        # Run specific test
        cmd = ["./gradlew", "testDebugUnitTest", "--tests", "*SlackWebhookValidatorTest"]
        result = subprocess.run(
            cmd,
            capture_output=True, text=True, timeout=120
        )
        
        passed = result.returncode == 0
        actual = "Tests passed" if passed else "Tests failed"
        
        return VerificationResult(
            function_id="CF-005",
            scenario_name="Webhook Validation Logic",
            passed=passed,
            actual_output=actual,
            expected_output="Tests passed",
            error_message=None if passed else result.stderr[:200], # truncated error
            interpretation="Validator logic is verified by unit tests." if passed else "Validator tests failed."
        )

    except Exception as e:
        return VerificationResult(
            function_id="CF-005",
            scenario_name="Webhook Validation Logic",
            passed=False,
            actual_output=str(e),
            expected_output="Tests passed",
            error_message=str(e),
            interpretation="Failed to execute gradle tests."
        )

def main():
    print("=" * 60)
    print("CORE FUNCTION VERIFICATION REPORT")
    print("=" * 60)

    # For now, we only verify CF-005 as it is a pure logic function easiest to unit test first.
    # Other CFs require more complex mocking (Android environment).
    results = [
        verify_cf005_webhook_validation(),
    ]

    passed_count = sum(1 for r in results if r.passed)
    total_count = len(results)

    for r in results:
        status = "✅ PASS" if r.passed else "❌ FAIL"
        print(f"\n{status} [{r.function_id}] {r.scenario_name}")
        print(f"  Interpretation: {r.interpretation}")
        if r.error_message:
            print(f"  Error: {r.error_message}")

    print("\n" + "=" * 60)
    print(f"SUMMARY: {passed_count}/{total_count} passed")

    # Result JSON
    output_path = Path(".audit/output/verification_result.json")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(
        [r.__dict__ for r in results],
        ensure_ascii=False, indent=2
    ))

    sys.exit(0 if passed_count == total_count else 1)

if __name__ == "__main__":
    main()
